Первая проверка 13 спринта
madromk/java-shareit pull request #1
Opened 2022-08-23 21:29 UTC by madromk

2022-08-26 11:30 UTC, Fleaman777 requested changes

2022-08-26 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Item> addItem(@RequestHeader(value = "X-Sharer-User-Id", required = false) Integer userId,
Название хэдера можно вынести в консонанту

2022-08-26 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (new ValidateItemData(item).checkAllData()) {
ValidationItemData может тоже сделать в виде Спринг компонента и заавтовайрить его

2022-08-26 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
Хорошо тип сделать более широкий Мар, так лучше будет работать полиморфизм

2022-08-26 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +            }
Хороший кандидат на то, что бы эту логику сделать через стрим

посмотри другие форичи на этот счёт, может что-то тоже можно переделать

2022-08-26 11:30 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        if (new ValidateUserData(user).checkAllData()) {
Здесь аналогично, ValidationUserData можно будет запвтовайрить

2022-09-01 14:19 UTC, avfyodorov reviewed
Добрый день! 

Замечание всего одно, к мелочи я придираться не стал. Но здесь надо разобраться-где какой класс и в каком слое обитает.

2022-09-01 14:19 UTC, avfyodorov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<User> addUser(@RequestBody User user) {
Здесь не должно быть объектов БД. Он же пришёл снаружи, значит должен быть dto.
Передаётся в слой сервиса как dto, там  происходит обработка, а перед там как передать в слой репозитария, делается маппинг в простого юзера.
Впрочем, маппинг можно делать и на входе в сервис. На Ваше усмотрение.
Ну и так далее, по остальным методам и остальным классам. Проверьте пожалуйста.
Общий принцип такой-контроллеры - это dto, сервисы это бизнес логика и маппинг, а репозиторий это обычные классы для работы в базе данных.

2022-09-05 18:28 UTC, avfyodorov reviewed
Добрый день!

Замечаний нет.
Работа принята.

2022-09-07 17:23 UTC, merged