Проверочный пуш для ветке add-docker
madromk/java-shareit pull request #4
Opened 2022-10-09 19:05 UTC by madromk

2022-10-15 09:19 UTC, Fleaman777 requested changes

2022-10-15 09:19 UTC, Fleaman777 commented on .github/workflows/api-tests.yml
> +    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci
правильно понима, что эти все изменения в api-tests были даны изначально ? 
и ты ничего в них не правил ?

2022-10-15 09:19 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к просто Dockerfile

2022-10-15 09:19 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
здорово, что валидацию делаешь черезе аннотации, это очень хорошо улучшает восприятие кода

2022-10-15 09:19 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +        String authorName;
поля должны быть private

2022-10-15 09:19 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
можно еще использовать такую конструкцию: spring.datasource.username=${POSTGRES_USER:user}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение user

2022-10-15 10:39 UTC, madromk commented on .github/workflows/api-tests.yml
> +    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci
Не совсем. Нас попросили внести изменения в этот файл когда мы будет делать ФЗ 16 спринта. Отправил тебе в личку в слаке скриншот

2022-10-17 06:48 UTC, Fleaman777 approved these changes

2022-10-17 06:51 UTC, merged